### ISSUE TITLE
invisible recaptcha + laravel-jsvalidation

### ISSUE THREAD

**Issue by garbinmarcelo** [ARCANEDEV/noCAPTCHA#54]
- noCaptcha Version:  4.0.1
- Laravel Version: 5.4.27
- PHP Version: 7.0.10

### Description:
How do I use the invisible recaptcha with the laravel-jsvalidation or jQuery Validation Plugin?

The problem is that there is apparently a conflict at the time of submitting the form. So the form is sent without being validated by javascript.

I'm using this package with noCAPTCHA: https://github.com/proengsoft/laravel-jsvalidation

P.S.: Without being the invisible recaptcha mode, the behavior of recaptcha, javascript validation in the form is normal.

**Comment by arcanedev-maroc** [comment]
Sorry, i can't help you with this because i don't know how the `proengsoft/laravel-jsvalidation` package or `jQuery Validation Plugin` works.

Just keep in mind that you can trigger any js script before submitting the form: https://github.com/ARCANEDEV/noCAPTCHA/blob/master/examples/invisible-captcha.php#L27-L31

This is the same as the official guide: https://developers.google.com/recaptcha/docs/invisible#auto_render
