### ISSUE TITLE
InvisibleCaptcha not working on Laravel 5.5

### ISSUE THREAD

**Issue by AdrianKuriata** [ARCANEDEV/noCAPTCHA#66]
- noCaptcha Version: Latest
- Laravel Version: Latest 5.5
- PHP Version: Latest 7.1

Hi, i have a problem with recaptcha. I created a recaptcha in google developer like a invisible recaptcha, i added keys to ENV file. Put recaptcha and scripts to form but i see recaptcha like a recaptcha V2, not like a invisible. I don't know what can i do with it. When i remove captcha key i getting error for key is wrong for my page, but when is good i see recaptcha, here is a picture: [https://i.imgur.com/haos1yT.png](https://i.imgur.com/haos1yT.png)

### Steps To Reproduce:
Install with docs for laravel.

**Comment by arcanedev-maroc** [comment]
Did you used the same example as [this](https://github.com/ARCANEDEV/noCAPTCHA/blob/master/_docs/3-Usage.md#invisible-captcha) ?

For laravel, instead of `$captcha->button('Send', ['data-badge' => 'inline']);` you can use the facade: `Captcha::button('Send', ['data-badge' => 'inline'])`

Check also these issues for more details: #53, #50
